import type { Metadata } from 'next'
import { StudyPlanGenerator } from './StudyPlanGenerator'
import { SITE_URL, SITE_NAME } from '@/lib/site'
import { RevealOnScroll } from '@/components/RevealOnScroll'

export const metadata: Metadata = {
  title: 'AI Study Plan Generator — Free Personalized OET Prep Plan',
  description:
    'Enter your current OET scores, target regulator, exam date, and weekly hours — get a free AI-generated week-by-week study plan prioritizing your weakest sub-test.',
  alternates: { canonical: '/tools/ai-study-plan-generator' },
}

const FAQS = [
  {
    q: 'Is this plan personalized to me?',
    a: "Yes. It's generated by AI from the exact scores, target regulator, exam date, and weekly hours you enter — it prioritizes whichever sub-test is furthest from your target and paces the plan to your timeline, not a generic template.",
  },
  {
    q: 'Is it free?',
    a: "Yes, no signup required. It's rate-limited per visitor to keep the tool available for everyone, so if you hit the limit, wait a while and try again.",
  },
  {
    q: 'Is my data saved?',
    a: 'No scores or personal data are stored. The request generates your plan and returns it directly — nothing is written to a database beyond an anonymous cost-tracking record with no personal data in it.',
  },
  {
    q: "How is this different from SpeakOET's Elite AI coach?",
    a: "This tool generates a one-time plan from numbers you type in. The Elite AI coach (available after signup) builds an evolving plan from your actual practice session history — it gets more accurate the more you practice, and updates automatically instead of being a single snapshot.",
  },
]

const faqJsonLd = {
  '@context': 'https://schema.org',
  '@type': 'FAQPage',
  mainEntity: FAQS.map(({ q, a }) => ({
    '@type': 'Question',
    name: q,
    acceptedAnswer: { '@type': 'Answer', text: a },
  })),
}

const softwareApplicationJsonLd = {
  '@context': 'https://schema.org',
  '@type': 'SoftwareApplication',
  name: `AI Study Plan Generator by ${SITE_NAME}`,
  applicationCategory: 'EducationalApplication',
  operatingSystem: 'Web',
  url: `${SITE_URL}/tools/ai-study-plan-generator`,
  description: 'Free AI-generated OET study plan for nurses, personalized to current scores, target regulator, and exam date.',
  offers: { '@type': 'Offer', price: '0', priceCurrency: 'INR' },
}

export default function AiStudyPlanGeneratorPage() {
  return (
    <main className="min-h-screen bg-gray-50">
      <script
        type="application/ld+json"
        // eslint-disable-next-line react/no-danger
        dangerouslySetInnerHTML={{ __html: JSON.stringify(faqJsonLd) }}
      />
      <script
        type="application/ld+json"
        // eslint-disable-next-line react/no-danger
        dangerouslySetInnerHTML={{ __html: JSON.stringify(softwareApplicationJsonLd) }}
      />

      <div className="max-w-4xl mx-auto px-4 py-16">
        <div className="text-center mb-10 motion-safe:animate-[fade-up-in_0.5s_ease-out_both]">
          <h1 className="font-display text-4xl md:text-5xl font-semibold text-[#0F2356] text-balance">
            AI Study Plan Generator
          </h1>
          <p className="text-gray-500 mt-4 text-lg max-w-2xl mx-auto">
            Enter your scores, target regulator, exam date, and weekly hours — get a free
            AI-generated week-by-week plan that prioritizes your weakest sub-test.
          </p>
        </div>

        <StudyPlanGenerator />

        <div className="max-w-3xl mx-auto mt-16">
          <h2 className="font-display text-2xl md:text-3xl font-semibold text-[#0F2356] text-center mb-8">
            Generator Questions
          </h2>
          <div className="rounded-2xl overflow-hidden border border-gray-100 shadow-premium bg-white">
            {FAQS.map((faq, i) => (
              <RevealOnScroll key={faq.q} delayMs={Math.min(i, 4) * 40} className={i % 2 === 0 ? 'bg-white' : 'bg-gray-50'}>
                <div className="px-6 py-5">
                  <h3 className="text-[#0F2356] font-semibold text-sm md:text-base leading-snug mb-2">
                    {faq.q}
                  </h3>
                  <p className="text-gray-600 text-sm leading-relaxed">{faq.a}</p>
                </div>
                {i < FAQS.length - 1 && <div className="border-b border-gray-100" />}
              </RevealOnScroll>
            ))}
          </div>
        </div>
      </div>
    </main>
  )
}
